### ISSUE TITLE
Comparisons of the "adhesinome" of C. auris and C. albicans?

### ISSUE THREAD

**Issue by hezhaobin** [binhe-lab/C037-Cand-auris-adhesin#1]
Now that Lindsey has done genome-wide predictions for adhesins in _C. auris_, are there ways to make broad-stroke comparisons of the adhesinome between _C. auris_, _C. albicans_ and _C. glabrata_? For example, what is the number of predicted adhesins in each species, how about the percent of them that have predicted signal peptide, GPI anchors and well-folded N-terminal domains? How about cystein-rich repeats? A comprehensive comparison will probably take significant amount of time. The priority is to identify a few parameters, such as number of predicted adhesins and sequence length, signal peptide (there are web-based algorithms that one can easily run), and draw some simple conclusions.

One question: the FungalRV authors already applied their algorithms to _C. albicans_ and _C. glabrata_. We should download them and see what format are those results.

**Comment by rsmoak** [comment]
1. Prediction results
- My first question as a reviewer would be why we chose to run only the FungalRV predictions through FaaPred and not the entire proteome through both so we could also see what FungalRV rejected from FaaPred. We could still use the union (which should be the same results as what we have now) for further analysis, but it might give us an idea of what specific characteristics of the proteins that we are examining are actually driving the proteins being predicted as adhesins.
- My second question as a scientist would be intragenome and intergenome comparisons in the _C._ _auris_ genomes. How many protein families are we looking at in each genome? Are they the same protein families in both genomes? I think this is an interesting question, because depending on how these end up splitting, Lindsey and I have run two case studies on one protein family or one case study each on two protein families; I was never actually convinced either way. We never actually decided which was likely the case. Also, if we are presenting them as case studies, we need to have a reason for selecting the proteins we used for examination.

2. FungalRV author results
- I downloaded and looked at the supplementary data from the FungalRV paper. I've condensed the useful information into a single Excel file, which I have uploaded with my comment (I don't seem to have push permission to actually upload them to a folder). It looks like the authors actually applied the algorithm to the entire proteomes of _C._ _albicans_, _C._ _glabrata_, _C._ _dubliniensis_, _C._ _tropicalis_, _C._ _guilliermondii_, _C._ _lusitaniae_, and _C._ _parasilosis_. They posted the locus tags and scores of the proteins that exceeded their cutoff of 0.511. I've compiled a list of the locus tags for each in the first sheet of the Excel file; a copy of the first worksheet is also attached in the text file. My only caution with using these as-is is that the authors have updated the FungalRV algorithm since publishing the paper, so we can't be sure that all of these would still be results (although that's a simple check) or that these would be exhaustive results. We could run the results through FaaPred as well.
[Smoak_Chaudhuri_Predicted_Loci.txt](https://github.com/binhe-lab/C037-Cand-auris-adhesin/files/4180932/Smoak_Chaudhuri_Predicted_Loci.txt)
[Smoak_Chaudhuri_Combined_SI.xlsx](https://github.com/binhe-lab/C037-Cand-auris-adhesin/files/4180933/Smoak_Chaudhuri_Combined_SI.xlsx)
-As a note, the FungalRV algorithm and its component programs are available in the Downloads tab of the FungalRV website. We might be able to use the component programs to give us a clue about what feature(s) is/are contributing most strongly to the adhesin predictions.

3. Broader comparisons
-I like the idea of following the Lipke 2018 Table 1 as a template; that's what I did in my final paper as well. It was for the most part quite simple. _C._ _albicans_ only has 81 predicted adhesins from the FungalRV authors' search and _C._ _glabrata_ has 65; if we run them through FaaPred first, we might not actually have a list that is too long of the _C._ _auris_ predicted adhesins and the adhesins for comparison in _C._ _albicans_ and _C._ _glabrata_. 
-We might find that there isn't that much correspondence between the three species (that's what was suggested by my results and also in the Lipke 2018 paper more generally), so depending on the results it might be nice to include a comparison to something that is more closely-related to _C._ _auris_ as well, like one of the three _haemulonii_ species, if our results indicate that the putative adhesins in _C._ _auris_ don't follow the same patterns as the more well-studied species. This would, to me, at least suggest that there are whole classes of fungal adhesins that are fundamentally different than the ones that are well-studied, which is a larger issue than just the adhesins in _C._ _auris_. I'm curious about these results.
-When comparing between species, are we thinking about presenting results as averages, ranges, or something else? Sequence length, for example, can be quite divergent in the predicted adhesins. There are ways that we could put a small plot in a table to visually demonstrate this (think a violin plot in a table column; you can do it in R), but I think that a single value might not really represent it well. We might find similar things with other parameters.
-As a note for comparison parameters: in the 63 sequences in the homolog group I looked at for my project, there were no cysteine-rich repeats identified (which could be interesting since other known adhesins tend to have them). T- and S- rich regions and dibasic sequences are easy to identify and were much more prominent in the species I looked at. 


Those are my thoughts so far, let me know what y'all think.

**Comment by hezhaobin** [comment]
Great questions and ideas, Rachel!
1. Prediction
    a. Lindsey ran only the FungalRV ones through FaaPred because the latter tool doesn't have its source code available for download and the website has a limit of running 25 sequences at a time. We could contact the authors and get their suggestions, or we could find a way to justify this strategy (Lipke 2018 made a brief comparison of the two tools).
    a. We surely should look into within-species (inter-genome?) variability. I believe Lindsey already have the tally (just compare the results for B11221 and B8441). Are they 100% identical? If not, are the differences due to assembly quality or genuine biological differences?

2. Thanks for the condensed table. As for running the program, I've looked into that yesterday and have downloaded their source code. I need to compile their c-code and test them locally. There are a few standalone programs that may be useful for us, including ones that calculate amino acid and di-peptide frequencies (think for calculating Cysteine-richness).

3. Those are very good ideas. Lindsey, can you look into these and give your thoughts?

Lastly, Rachel, I've invited you to be a collaborator on this repo. Test to see if you have push permissions now.

**Comment by janfassler** [comment]
Hi guys,  I don't have much time right now, but I wanted to leave some initial reactions: 
I agree with Rachel that we may miss some candidates if we don’t put the entire proteome through each of the prediction tools.  I’m envisioning some type of Venn diagram with the three sets defined in the supplement and pursuit of the members of the intersection.

I think we might be able to get to number of families by making our own definitions.  If we made our own version of Lipke Table 1 with all the members of the intersection for any given genome, using the original column headers plus others that case studies have shown may be relevant, we could then create families based on conservation of a certain number or specific types of features.  This is where such annotations as “Als2-like” come from.  From there it will be simpler to make comparisons between proteomes.  For example, how many “Als2-like” family members are there in each?  This will also allow us to annotate (and name) unique families.

If we wish to discuss how specific features may have become specialized within species leading to inter-proteomic distinctions, we can certainly focus on ranges (size of the feature, number of repeats,  relative location of the feature within the protein) and do ANOVA tests to ascertain if the differences are significant.

**Comment by rsmoak** [comment]
I was investigating the idea of using the FungalRV pre-prepared list of identified adhesins, so I downloaded the proteome from the newest RefSeq assembly and ran it through FungalRV. Using the cutoff of 0 (which is the current recommendation and what we did for our _C._ _auris_ proteomes, there are 142 potential adhesins in _C._ _glabrata_ (for reference, using the 2004 data that the original paper was based on and the current algorithm, there were 62 above the 0.511 cutoff - same as the paper found - and 142 above 0 - the same ones that the current genome build gives). Doing the same for the current build of _C._ _albicans_ gives 231 with score > 0 and 84 with score > 0.511 (the original paper had 81 with score > 0.511).

These are different enough from the list reported in the FungalRV paper that I think for a methodologically sound comparison, we need to use the new RefSeq assemblies and the most updated version of FungalRV. Hopefully, also running these through FaaPred will decrease the list of proteins to look at for comparison. I can work on that in batches of 25 gradually over the next few days if we don't hear back from the author. I'll upload files when I figure out how (I'm still getting the you need push permissions error - it is probably user error at this point. I'll look into it.)

Also be warned, copying and pasting sequences into FungalRV in FASTA format and uploading the file that you copied and pasted from do not necessarily give the same results. I'm unsure why. When I downloaded the current _C._ _glabrata_ build from the FTP, unzipped it, and uploaded the .fas file (or a .txt from the .fas), FungalRV predicted that 80% of the proteins were adhesins (over 4000). When I pasted that same file in, it only predicted 142. I tried batch downloading from the NCBI website all of the _C._ _glabrata_ proteins and both uploading and pasting that; both worked fine. The issue seemed to only happen with the file from the FTP. Like I said, I don't know what the underlying issue is.

**Comment by hezhaobin** [comment]
I agree that we should rerun FungalRV using the latest version on the most recent genome build for _C. albicans_. 

For the file format difference, if you accept the invitation and start to commit the results you got to the repo, I can take a look. You can follow the folder structure we already established, i.e. in 01-global-prediction/analysis, data, output, script, or, you can create a new subfolder and lay out your results there, perhaps calling it 02-new-genome-prediction, etc.

**Comment by hezhaobin** [comment]
Rachel, great work on getting all the sequences through FungalRV and FaaPred. I'll update you here after I discuss with Lindsey about the next steps.

**Comment by hezhaobin** [comment]
What I have done:
1. updated some of the README files in `data` and `output` folders.
1. created symbolic links from the predicted adhesin fasta files in the output folder into a new folder in `data`. this is so that we collect all the predicted adhesins in one place to facilitate the next batch of analysis.
1. after chatting with Lindsey and Jan, we think we should start collecting sequence features for all the predicted adhesins. The goal is to have a master spreadsheet that has each predicted adhesin as one record, documenting its species origin, gene ID, sequence features such as 
    a. cysteine content, dibasic peptide content -- Bin will look into these
    b. signal-peptide, GPI prediction, N- and O-glycosylation -- Lindsey will look into these
    c. N-terminal domain (?), Beta-aggregation (TANGO), tandem repeats (?) -- Rachel?

**Comment by rsmoak** [comment]
I'd be happy to look into the three of them, but I have a few questions:
- N-terminal domain: what precisely are we looking for here? Lipke 2018 lists three domains that have been identified; am I just screening for any of the three of them present in each sequence?
- Beta-aggregation: TANGO requires several input parameters. I want to make sure that the values for each are reasonable before running all of them:
Cter = status of the C-terminus of the peptide (amidated Y, free **N**)
Nter = status of the N-terminus of the peptide (acetylated A, succinilated S and free **N**)
pH = pH **7**
Temp = temperature in Kelvin **298**
Ionic = ionic strength in M **0.1**
- Tandem repeats: my understanding is that you often search nucleotide sequences for these. Do we need nucleotide sequences or do protein sequences also work?

**Comment by hezhaobin** [comment]
Sorry for the slow response. We are interviewing Ph.D. candidates these two days, schedule is a bit crazy.

I have to say that I don't have perfect answers for your questions. All these are also questions I'm wondering myself. But here are some thoughts:

1. A well folded domain could mean a) not consisting of tandem or other repetitive sequence AND b) have predicted secondary structure AND/OR c) match well known domains, such as through a PROSITE search. As for how to practically analyze these, all I can think about is to take a few example sequences and play with PROSITE and other secondary structure prediction algorithms. If I were to do this, I would actually leave it to the last, as it feels like a lot of manual work.
1. I have not used TANGO before. I'll need to read up on its manual and also refer to the information cited by Lipke 2018 (I think he cited some other paper on this parameter).
1. Not sure myself. Again, will need to use the references in Lipke 2018 to investigate.

I'll have more time this Saturday. Will look into some of these problems.

**Comment by lindseyfaye** [comment]
I thought I would leave my opinions on Rachel's questions here:
1. I think initially I would just separate predicted adhesins that do and do not contain a well characterized N-terminal domain.
2. I looked at the Lipke paper to see if they mentioned anywhere what parameters they used in their TANGO search and didn't find anything. I think I would first try their default parameters or even look into more user friendly tools. I did a basic search and found AGGRESCAN (http://bioinf.uab.es/aggrescan/), which at first glance looks easier to use and doesn't require any parameters.
3. As for the tandem repeats, I'm not completely sure and you could try both but considering we discovered the presence of the repeats in our proteins through MSA and MeMe analysis using the protein sequences I think we could defend using the protein sequences.

Hope that helped a little, let me know if there's anything I can do to help. I have added predicted signal peptide and GPI anchor information for all strains and am working on figuring out the best way to compile the glycosylation predictions.

**Comment by hezhaobin** [comment]
Lindsey, can you add README.md to all the output folders, include information such as URL of the online tool and reference for that tool (pmid is fine). If there are no parameters needed to run the tool, say so in the README.

**Comment by hezhaobin** [comment]
@rsmoak here is a list of "tandem repeats" search algorithm I found. can you test them and figure out how they perform?
https://www.expasy.org/resources/search/keywords:sequence%20repeats

**Comment by hezhaobin** [comment]
Awesome work guys! @rsmoak @lindseyfaye

**Comment by rsmoak** [comment]
I ran TANGO with parameters I found in the literature and uploaded results.

@hezhaobin I saw that list and looked at all of them last week. I decided to use XSTREAM after reading papers about most of them. The default parameters do allow a bit of fuzziness in the matching, but I can change that and rerun if we want; one of the reasons I chose XSTREAM is that it can run all of the sequences in less than a minute with similar results as the algorithms that take a few hours. I could also download it and its documentation was pretty good. I uploaded the results from the run with the default parameters.

I'm still having trouble with the N-terminal domain. @lindseyfaye what do you mean when you mention filtering based on having a well characterized N-terminal domain? I've tried screening for known conserved domains, but haven't gotten results in the week since I've submitted the sequences to NCBI's Conserved Domain tool or tried searching against pfam with hmmer. I'll try Prosite. Let me know if anyone has any suggestions

**Comment by lindseyfaye** [comment]
@rsmoak You're doing exactly what I would do, the only other thing you could try is Interpro because I think they have an option to download to be able to run the sequences in batch.

**Comment by hezhaobin** [comment]
@rsmoak , for "well-folded N-terminal domain", I have also struggled to understand what it is. My current thought is, maybe it is really defined by "what it is not", namely tandem repeats and disordered region. So there are two potential ways to go about it:
1. predict disordered regions. see if the first N amino acids from the N-terminal, e.g. 100-300, do not contain predicted disordered regions.
2. secondary structures as a proxy for "well folded domains". I'm not knowledgeable enough to know if this approximation is sensible.

**Comment by janfassler** [comment]
Yes, I think the methods you suggest are sensible.  Another way would be to submit protein N termini as queries to the protein fold databases CATH or SCOP.  One further way would be to submit examples from any given "cluster" to iTASSER to identify related folds by threading.  I'm running tests now to see if the output seems relevant and if any of these programs can be run in batch mode.

**Comment by janfassler** [comment]
Here's an example of output from CATH for one of the C. auris proteins from the FungalRV prediction spreadsheet.  The identified domains match known structures.  The links take you to an image of the structure, and the sequence coordinates of the region 
![image](https://user-images.githubusercontent.com/60896065/74956602-f7dace80-53cb-11ea-929d-1f803fa81d79.png)

![image](https://user-images.githubusercontent.com/60896065/74957017-8ea78b00-53cc-11ea-815b-b153b5067a86.png)

**Comment by hezhaobin** [comment]
@janfassler great! I think the key then is to figure out if this can be run in batch. If we can capture the output as a text file and just parse the information regarding the position of the predicted domain, then calculate the "relative position" in the protein to determine, say if that prediction is located in the first 1/3 of the protein, Y/N. That can be a column in the result table.
When discussing this with @lindseyfaye, we thought a general strategy can be:
1. anything we can run in batch and whose results can be summarized as a number or a simple string, we will do it genome-wide
1. anything that requires more manual curation, e.g. phylogenetic analysis, we do it for selected representatives. essentially, that's the analyses that @lindseyfaye and @rsmoak already did for the course. but we can add, say, domain prediction to the selected list of analyses as well.

**Comment by rsmoak** [comment]
I like CATH, it looks like it has the functionality we need and it is fast. I couldn't find a downloadable version to run a batch in; instead, it looks like they have a web API that we could post sequences to one by one (parsed from a file with all of the sequences) and get results (see [here](http://www.cathdb.info/search/by_sequence#api)). The output should have domain hits, their locations, and their scores. A couple of test cases that I ran came back with a bunch of overlapping domains, which I don't think we want. The same group has a downloadable program on their [github](https://github.com/UCLOrengoGroup/cath-tools) that will [resolve overlapping domains](https://cath-tools.readthedocs.io/en/latest/tools/cath-resolve-hits/). The output should have the non-overalpping domains and threir locations. The domains in their program are named by a [hierarchical structure classification](http://www.cathdb.info/browse/tree), so I suspect the returned domain names can be used as a proxy for structural similarity in the same regions of different proteins, especially since I think they have a downloadable version of the node names in [cath-b-20170519-names-all.gz](https://www.cathdb.info/download). 

I can give this a shot, but it is one of those cases where some more experience might greatly speed the process. If someone else wants to try this, let me know.

CATH also has some other interesting [tools](https://www.cathdb.info/) if anyone is interested.

**Comment by hezhaobin** [comment]
@rsmoak @lindseyfaye , I have figured out how to talk to CATH through the command line, using `cURL`, and parsing the output using `jq`.  Where I'm not sure about is what exactly is the information we want from the output. The graphic user result will show a number of predictions. Here are two types of answers we possibly can summarize:
1. We just want to know if the N-terminal has matches to known domains or not. This is possibly easy, because I can output the positions of the predicted domains, and just do some arithmatics
2. We also want to classify the domains, perhaps using the `cath-resolve-hits` tool @rsmoak mentioned. The challenge here is, I haven't figured out how to format the CATH web api output to something the tool can take as input.
Just want to give you guys an update, since I'll have to finish some teaching stuff this weekend before I can come back to this.

**Comment by rsmoak** [comment]
@hezhaobin I saw the CATH genome tool and ran the analysis on all of the predicted adhesins. When I was looking at the results, I realized that CATH has no domain that corresponds to pfam PF11765, which was the domain that I (and @lindseyfaye I think) used to locate our project proteins in the first place; it is a cell wall protein N-terminal. My project protein has no predicted domains in it, and @lindseyfaye's has a 50aa domain repeated three times throughout it. I haven't uploaded the full results yet; I'll parse through them and attach what the levels for the domains mean first. I did drop the html output into the data folder if you want to look at it.

The question, though, is if we think CATH gives us the information we want. I'm still waiting on the results for searching the pfam database with hmmscan, and will probably look at comparing the results of the two methods once it is done.

**Comment by hezhaobin** [comment]
great progress @rsmoak ! I looked up CATH and Pfam differences. According to [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4612221/), Pfam classifies protein based on sequence homologies while CATH uses structure. For your protein, the PF11765 probably get its ID in Pfam because there are publications studying some representative gene in this family in _C. albicans_, and a sequence homology search found a bunch of them (500 on Interpro), hence the family. However, since there is no structure for it, CATH wouldn't pick that up. I think we should finish CATH first and parse its results, after which we can decide if we also want Pfam on the same set.

When I was looking at the results of the cath genome tool, I found the `.crl` file the most useful, as it simply lists the resoloved hits one record per row. In R, one can easily sort them by query sequence ID and then take minimum of the left boundary, maximum of the right boundary, and concatenate the hit IDs into a comment field. This will produce a BED / GFF formatted output that is easy to be interrogated further.

One more thing: a new paper from Brendan Cormack group (giant in _C. glabrata_ field) just released a [new version](https://www.ncbi.nlm.nih.gov/pubmed/32068314) of the _C. glabrata_ type strain genome, resolving many tandem repeat regions and discovered a bunch more Cell Wall Integrated proteins. @lindseyfaye is working on repeating the FungalRV and Faapred analysis on the latest version of the genome.

**Comment by rsmoak** [comment]
@hezhaobin I wasn't precisely sure what you were envisioning, so I am going ahead and posting my parsing of the .crl file under the CATH output folder. I've also updated the results table to include whether any domains were found using CATH and whether any of them started within the first quarter of the sequence length.

I (obviously) used the old *C. glabrata* data, but that is easily updated once @lindseyfaye finishes the new analysis.

**Comment by hezhaobin** [comment]
@rsmoak , saw your results and the parsed files look great. Note however currently you have one or more records for each protein entry. We would want one record per entry. One idea is, as you suggested, to just record Y/N of whether there is a predicted domain in the first 1/4 of the sequence. Of course, with the parsed results saved for each genome, it is easy to go back and ask different questions.

**Comment by rsmoak** [comment]
@hezhaobin I have T/F recorded for each protein in the larger combined results table since CATH didn't return proteins where no domain was found at all. The output files have all of the raw output, including multiple domains where different domains were found on the same protein (or the same domain was found multiple times on the protein).

I can post a version of the T/F with just the CATH results if people think it would be helpful; I can just cut it out of the larger table.

**Comment by hezhaobin** [comment]
@rsmoak you can leave the Y/N results in the master table. Once @lindseyfaye confirm that the new _C. glabrata_ prediction result is ready, let's all rerun the previous analyses on that new version, then @rsmoak you will need to update the master table. Did you write a R script to combine the results or was it in an interactive session? If the latter, can you, this time, write those into an Rmarkdown (in RStudio)? Let me know if you have any questions.

Plan for this and next week
1. Finish all genome-wide analyses, with the new Cg genome (I'll finish the amino acid composition)
1. Construct the master result table and make sure it is reproducible (with an RMarkdown document)
1. Exploratory analysis to visualize global differences in the adhesinome properties among the species
1. Finally, we will get into the stage of constructing figures. Something exciting to look forward to.

Lastly, @rsmoak did you run your protein through I-Tasser? I don't recall seeing a structural result in your report. Perhaps you did but the result is not interpretable?

**Comment by rsmoak** [comment]
@hezhaobin Right now, it was a combination of R scripts and an interactive session to make the master table. I haven't used Rmarkdown before, but I'll try and compile it all (it is mostly running a series of functions, which it looks like should be easy to put into a markdown file?).

As an fyi, all of my R scripts are set up to work on a files containing the adhesins from all species, so it would be helpful to me if people rerun individual analyses and then just combine the outputs from all species into a single text file as well as updating the text files in the C. glabrata folders. I can join results by pretty much any version of the sequence tag as long as it in included somewhere.

I did run my protein through I-Tasser and I have the results saved. I didn't include it in my report because the results weren't very statistically significant and I'd already written most of my report by the time they came back, but I can post them if you'd like.

As another fyi, results are coming back today and tomorrow for the hmmscan of all the proteins against pfam. I've already written a parsing function, so I'll probably include the results in the master table so we can compare them to the CATH results. I'll submit the new Cg proteins after we have them for comparison, but I suspect that will be the slow step in the analysis. I'll post a new version of the master results table before they finish if it takes too long.

**Comment by lindseyfaye** [comment]
FungalRV is predicting around 1000 adhesins in the new C. glabrata proteome, this seems suspicious considering the total size of the proteome is the same. This is too many adhesins to run through Faapred so I talked to @hezhaobin and will leave the analysis there for now. I will upload the fungalRV output shortly. Let me know if you have any suggestions.

**Comment by hezhaobin** [comment]
> @hezhaobin Right now, it was a combination of R scripts and an interactive session to make the master table. I haven't used Rmarkdown before, but I'll try and compile it all (it is mostly running a series of functions, which it looks like should be easy to put into a markdown file?).
> 
> As an fyi, all of my R scripts are set up to work on a files containing the adhesins from all species, so it would be helpful to me if people rerun individual analyses and then just combine the outputs from all species into a single text file as well as updating the text files in the C. glabrata folders. I can join results by pretty much any version of the sequence tag as long as it in included somewhere.
> 
> I did run my protein through I-Tasser and I have the results saved. I didn't include it in my report because the results weren't very statistically significant and I'd already written most of my report by the time they came back, but I can post them if you'd like.
> 
> As another fyi, results are coming back today and tomorrow for the hmmscan of all the proteins against pfam. I've already written a parsing function, so I'll probably include the results in the master table so we can compare them to the CATH results. I'll submit the new Cg proteins after we have them for comparison, but I suspect that will be the slow step in the analysis. I'll post a new version of the master results table before they finish if it takes too long.

For Rmarkdown, it's a document that mixes narrative and code. Narratives are written in markdown format, while r code is enclosed in between 
```{r}
# your code here
```
Example: https://github.com/hezhaobin/more-pho/blob/master/E032-Pho4-in-oxidative-stress/analysis/qPCR/20181024-oxidative/qPCR_analysis_20141125.Rmd

**Comment by hezhaobin** [comment]
> FungalRV is predicting around 1000 adhesins in the new C. glabrata proteome, this seems suspicious considering the total size of the proteome is the same. This is too many adhesins to run through Faapred so I talked to @hezhaobin and will leave the analysis there for now. I will upload the fungalRV output shortly. Let me know if you have any suggestions.

I did a simple comparison of the protein length distribution between the old and new Cg sequences, and the difference is huge.

    ```r
    > require(data.table)
    > newL <- fread("NewCg-protein-length.txt", sep = "\t")
    > oldL <- fread("OldCg-protein-length.txt", sep = "\t")
    > fivenum(newL$V2)
    [1]   105   759  1263  1944 21711
    > fivenum(old$V2)
    [1]   34    255   420   646  4880
    #    min    25%  median 75%   max
    ```
I'm almost certain this is the cause of the bloated number of predicted adhesins. I'll need to find out what caused the difference in their length.

**Comment by hezhaobin** [comment]
> > @hezhaobin Right now, it was a combination of R scripts and an interactive session to make the master table. I haven't used Rmarkdown before, but I'll try and compile it all (it is mostly running a series of functions, which it looks like should be easy to put into a markdown file?).
> > As an fyi, all of my R scripts are set up to work on a files containing the adhesins from all species, so it would be helpful to me if people rerun individual analyses and then just combine the outputs from all species into a single text file as well as updating the text files in the C. glabrata folders. I can join results by pretty much any version of the sequence tag as long as it in included somewhere.
> > I did run my protein through I-Tasser and I have the results saved. I didn't include it in my report because the results weren't very statistically significant and I'd already written most of my report by the time they came back, but I can post them if you'd like.
> > As another fyi, results are coming back today and tomorrow for the hmmscan of all the proteins against pfam. I've already written a parsing function, so I'll probably include the results in the master table so we can compare them to the CATH results. I'll submit the new Cg proteins after we have them for comparison, but I suspect that will be the slow step in the analysis. I'll post a new version of the master results table before they finish if it takes too long.
> 
> For Rmarkdown, it's a document that mixes narrative and code. Narratives are written in markdown format, while r code is enclosed in between
> ```{r}
> # your code here
> ```
> Example: https://github.com/hezhaobin/more-pho/blob/master/E032-Pho4-in-oxidative-stress/analysis/qPCR/20181024-oxidative/qPCR_analysis_20141125.Rmd

By the way, @rsmoak , if you are not already using RStudio and not familiar with Rmarkdown, well, it would be a great tool for you, but for now you can also give me your interactive session history and I can document it.

**Comment by hezhaobin** [comment]
OK, I'm closing this thread as it is getting too long. Let's move to a new one @rsmoak @lindseyfaye @janfassler
